[profile.default]
src = 'contracts/src'
test = 'contracts/test'
out = 'contracts/out'
libs = ['contracts/lib']
solc = '0.8.15'

remappings = [
  '@eth-optimism/contracts-bedrock/=node_modules/@eth-optimism/contracts-bedrock',
  '@openzeppelin/contracts/=node_modules/@openzeppelin/contracts/',
  '@openzeppelin/contracts-upgradeable/=node_modules/@openzeppelin/contracts-upgradeable/',
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config