AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Resources:
  SBTUniversity:
    Type: AWS::Serverless::Function
    Properties:
      Handler: university.lambda_handler
      Runtime: python3.9
      AutoPublishAlias: live
      DeploymentPreference:
        Type: AllAtOnce # Or Canary10Percent5Minutes, Linear10PercentEvery1Minute, ...
      ProvisionedConcurrencyConfig:
        ProvisionedConcurrentExecutions: 1
      Events:
        HttpGet:
          Type: Api
          Properties:
            Path: '/'
            Method: post
