version: '3'

services:
  react:
    build:
      context: react
      dockerfile: Dockerfile
    environment:
      NODE_ENV: staging
    ports:
      - 3001:3001
  api:
    build:
      context: api
      dockerfile: Dockerfile
    volumes:
      - ./api/src/:/home/node/api/src
      - ./api/config/:/home/node/api/config
      - ./api/contracts/:/home/node/api/contracts
      - /home/node/api/node_modules
    environment:
      NODE_ENV: staging
      NODE_PATH: .
    networks:
      - main
    ports:
      - 3000:3000
    depends_on:
      - parity
  parity:
    image: appliedblockchain/parity-solo:latest
    restart: always
    volumes:
      - parity:/solo/chains
    ports:
      - 8545:8545
      - 8546:8546
    networks:
      - main
volumes:
  parity:
networks:
  main: