#!/bin/sh
yarn --frozen-lockfile
cat <<EOF > config.js
//generated by install.sh
const config = {
5: {
  'inflationAddress': '$1',
  'apiAddress': '$2',
  'chainName': 'Goerli',
  'testnet': true
}
}
EOF
